version: '3'
services:

  redis-sentinel1:
    image: lgatica/redis-sentinel:4.0.2
    container_name: sentinel1

    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26379
      - MASTERHOST=localhost
      - CLIENTHOST=localhost
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
    volumes:
      - "../../sentinel-data/sentinel1:/redis"
    restart: always

  redis-sentinel2:
    image: lgatica/redis-sentinel:4.0.2
    container_name: sentinel2

    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26380
      - MASTERHOST=localhost
      - CLIENTHOST=localhost
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
    volumes:
      - "../../sentinel-data/sentinel2:/redis"
    restart: always

  redis-sentinel3:
    image: lgatica/redis-sentinel:4.0.2
    container_name: sentinel3

    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - MASTERPORT=6379
      - CLIENTPORT=26381
      - MASTERHOST=localhost
      - CLIENTHOST=localhost
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
    volumes:
      - "../../sentinel-data/sentinel3:/redis"
    restart: always