version: '3'
services:

  master:
    image: redis
    container_name: master
    
    ports:
      - 6379:6379

    volumes:
      - ./master:/redis

    command: redis-server /redis/redis.conf

  slave:
    image: redis
    container_name: slave
    
    ports:
      - 6380:6380

    volumes:
      - ./slave:/redis

    command: redis-server /redis/redis.conf

