version: '3'
services:

  master:
    image: redis
    container_name: master
    
    ports:
      - 6379:6379


    command: cp ./master/redis.conf /usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  slave:
    image: redis
    container_name: slave
    
    ports:
      - 6380:6380

    command: cp ./slave/redis.conf /usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

